### ISSUE TITLE
Can't compile the examples

### ISSUE THREAD

**Issue by StijnRuts** [newlandsvalley/webaudio-examples#1]
I can't get these examples to compile.

Steps to reproduce:
```
$ git clone git@github.com:newlandsvalley/webaudio-examples.git
$ cd webaudio-examples

$ bower install

Unable to find a suitable version for purescript-arraybuffer-types, please choose one by typing one of the numbers below:
    1) purescript-arraybuffer-types#^1.0.0 which resolved to 1.0.0 and is required by purescript-affjax#5.0.0, purescript-dom#4.15.0
    2) purescript-arraybuffer-types#^2.0.0 which resolved to 2.0.0 and is required by purescript-arraybuffer#6.0.0, purescript-webaudio#4e0972f8e4


$ bower install --force-latest

$ ./build.sh

Warning 1 of 12:

  in module Audio.WebAudio.MediaElementAudioSourceNode
  at bower_components/purescript-webaudio/src/Audio/WebAudio/MediaElementAudioSourceNode.purs line 3, column 1 - line 3, column 23

    The import of module Audio.WebAudio.Types is redundant


  See https://github.com/purescript/documentation/blob/master/errors/UnusedImport.md for more information,
  or to contribute content related to this warning.

Warning 2 of 12:
...


$ pulp --version
Pulp version 12.0.1
purs version 0.11.7

$ bower --version
1.8.2
```

**Comment by newlandsvalley** [comment]
OK - I'll take a look.  One thing I can do is to force a resolution in bower.json for arraybuffer-types.  This is annoying - the two versions are in fact identical.  Maybe this will  help.

**Comment by newlandsvalley** [comment]
Do you want to try again?

$ git clone git@github.com:newlandsvalley/webaudio-examples.git
$ cd webaudio-examples
$ bower install
$ ./build.sh  or $ pulp build

works for me

**Comment by StijnRuts** [comment]
I just tried it on my Linux box, and it did work.
(nearly identical version of all tools: pulp 12.0.1, purs 0.11.6, bower 1.8.2)

I'll try again on a MacBook tomorrow.
I assume something on this machine is to blame, my apologies.

Thanks for looking into this so quickly.

**Comment by newlandsvalley** [comment]
My pleasure! I'll leave this open for a day or two just in case there is a real underlying problem.
